import os
from .jon_zimage_sampler import NODE_CLASS_MAPPINGS as JON_ZIMAGE_SAMPLER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_ZIMAGE_SAMPLER_DISPLAY
from .jon_qwen_2511_sampler import NODE_CLASS_MAPPINGS as JON_QWEN_2511_SAMPLER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_QWEN_2511_SAMPLER_DISPLAY
from .jon_flux2_klein_9b_sampler import NODE_CLASS_MAPPINGS as JON_FLUX2_K_9B_SAMPLER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_FLUX2_K_9B_SAMPLER_DISPLAY
from .jon_wan22_sampler import NODE_CLASS_MAPPINGS as JON_WAN22_SAMPLER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_WAN22_SAMPLER_DISPLAY

from .jon_workflow_settings import NODE_CLASS_MAPPINGS as JON_WORKFLOW_SETTINGS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_WORKFLOW_SETTINGS_DISPLAY

from .jon_debug_node import NODE_CLASS_MAPPINGS as JON_DEBUG_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_DEBUG_NODE_DISPLAY

from .jon_lora_view import NODE_CLASS_MAPPINGS as JON_LORAVIEW_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_LORAVIEW_DISPLAY
from .jon_lora_model_only import NODE_CLASS_MAPPINGS as JON_LORA_MODEL_ONLY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_LORA_MODEL_ONLY_DISPLAY


from .jon_channel_mixer import NODE_CLASS_MAPPINGS as JON_CHANNEL_MIXER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_CHANNEL_MIXER_DISPLAY

from .jon_loader import NODE_CLASS_MAPPINGS as JON_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_LOADER_DISPLAY

from .jon_model_only_loader import NODE_CLASS_MAPPINGS as JON_MODEL_ONLY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_MODEL_ONLY_DISPLAY

from .jon_simple_math import NODE_CLASS_MAPPINGS as JON_SIMPLE_MATH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JON_SIMPLE_MATH_DISPLAY

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {
    **JON_ZIMAGE_SAMPLER_MAPPINGS,
    **JON_QWEN_2511_SAMPLER_MAPPINGS,
    **JON_FLUX2_K_9B_SAMPLER_MAPPINGS,
    **JON_WAN22_SAMPLER_MAPPINGS,
    **JON_WORKFLOW_SETTINGS_MAPPINGS,
    **JON_DEBUG_NODE_MAPPINGS,
    **JON_LORAVIEW_MAPPINGS,
    **JON_LORA_MODEL_ONLY_MAPPINGS,
    **JON_CHANNEL_MIXER_MAPPINGS,
    **JON_LOADER_MAPPINGS,
    **JON_MODEL_ONLY_MAPPINGS,
    **JON_SIMPLE_MATH_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **JON_ZIMAGE_SAMPLER_DISPLAY,
    **JON_QWEN_2511_SAMPLER_DISPLAY,
    **JON_FLUX2_K_9B_SAMPLER_DISPLAY,
    **JON_WAN22_SAMPLER_DISPLAY,
    **JON_WORKFLOW_SETTINGS_DISPLAY,
    **JON_DEBUG_NODE_DISPLAY,
    **JON_LORAVIEW_DISPLAY,
    **JON_LORA_MODEL_ONLY_DISPLAY,
    **JON_CHANNEL_MIXER_DISPLAY,
    **JON_LOADER_DISPLAY,
    **JON_MODEL_ONLY_DISPLAY,
    **JON_SIMPLE_MATH_DISPLAY
}

__all__ = ['NODE_CLASS_MAPPINGS',
           'NODE_DISPLAY_NAME_MAPPINGS',
           'WEB_DIRECTORY']
